### ISSUE TITLE
tlx.protect blocks some words instead of just prevent to execute it?

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#8]
I tested `tlx.protect()` and `protect` attribute (input element) and both prevent to type words like "alert" (it stops before the "t") instead of just protect to execute the injection. 

Is there a way to protect it globally instead of make it impossible to use the key words like "alert"?
Or is it possible to do a tlx.escape for input elements / data binding values?

**Comment by anywhichway** [comment]
We have to prevent the possibility of it being saved to a datastore also. How about these two things?

1) support automatic redefine of alert so it can't be used as a function
2) actually check for an open an open parentheses after the word alert ... allowing that there may be space in between.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pwFoo** [comment]
Check for "(" after the word would be better because of usage of for example "alert" as normal word in a sentence I think.

**Comment by anywhichway** [comment]
@pwFoo marked as a bug since we should have anticipated. Fixed in v1.0.24.

**Comment by pwFoo** [comment]
Hi @anywhichway ,

seems not fixed. Now it's possible to execute `alert("test")` with `tlx.protect()` or attribute `protect` added!
But without both it's prevented from execute.
So maybe just inverted the needed result...? *g*

**Comment by anywhichway** [comment]
@pwFoo Added an example in examples directory. Made a minor tweak to code also. Will push shortly,

**Comment by pwFoo** [comment]
Yes, looks good now.
`alert(` or `console. *` (also `console.` with space?) is blocked, but "With my console. *" works fine as text.
